CREATE NONCLUSTERED INDEX [IX_AnalysisSymptomIndicator_AnalysisId] ON [dbo].[AnalysisSymptomIndicator]
(
	[AnalysisId] ASC
)
INCLUDE([SymptomId],[IndicatorId]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



CREATE NONCLUSTERED INDEX [IX_SymptomIndicatorDeviationLevel_SymptomIdIndicatorId] ON [dbo].[SymptomIndicatorDeviationLevel]
(
	[SymptomId] ASC,
	[IndicatorId] ASC
)
INCLUDE([DeviationLevelId],[Comment]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



CREATE NONCLUSTERED INDEX [IX_AnalysisSymptom_SymptomId] ON [dbo].[AnalysisSymptom]
(
	[SymptomId] ASC
)
INCLUDE([AnalysisId],[Severity]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



CREATE NONCLUSTERED INDEX [IX_AnalysisSymptomIndicator_SymptomId] ON [dbo].[AnalysisSymptomIndicator]
(
	[SymptomId] ASC
)
INCLUDE([AnalysisId],[IndicatorId]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
